name: Production Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-assets:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: essembly_bot
            asset_name: essembly_bot-linux-amd64.tar.gz
          - os: windows-latest
            artifact_name: essembly_bot.exe
            asset_name: essembly_bot-windows-amd64.zip

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Pack Artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ${{github.workspace}}/build
        tar -czvf ../${{ matrix.asset_name }} ${{ matrix.artifact_name }}

    - name: Pack Artifact (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cd ${{github.workspace}}/build
        Compress-Archive -Path ${{ matrix.artifact_name }} -DestinationPath ..\${{ matrix.asset_name }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin-${{ matrix.os }}
        path: ${{matrix.asset_name}}

  publish-release:
    needs: build-assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          essembly_bot-linux-amd64.tar.gz
          essembly_bot-windows-amd64.zip
        generate_release_notes: true 